### ISSUE TITLE
导出多张图片无法对齐

### ISSUE THREAD

**Issue by Soupure** [hxj9102/table2excel#6]
导出多张图片无法对齐，有人遇到类似的问题吗

**Comment by OrangesFlower** [comment]
+1，我两个月前还是能对齐的，现在打开用这个功能就不能对齐了，请问解决了吗

**Comment by hxj9102** [comment]
麻烦提供下无法对齐的截图以及预期的效果、浏览器、浏览器版本，非常感谢！

**Comment by Soupure** [comment]
是chrome 浏览器 版本 112.0.5615.138  
![image](https://user-images.githubusercontent.com/32612930/236387808-45abf1d2-7fcc-4f39-974e-c30404189769.png)

**Comment by hxj9102** [comment]
thanks for your issues, the problem was solved in v1.1.2
